# Generated by Django 5.2.15 on 2026-06-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserWord",
            new_name="UsedWord",
        ),
    ]
