# Generated by Django 5.2.15 on 2026-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_roundguess"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("room",),
                name="one_active_game_per_room",
            ),
        ),
    ]
